/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.PermisoDAO;
import DTO.Permiso;
import DTO.Usuario;
import java.util.List;
import javax.swing.JFrame;

public class FrmPrincipal extends javax.swing.JFrame {

    public static Usuario usuarioLogged = null;

    private boolean _menuAdministracionDePermisos = false;
    private boolean _submenuRoles = false;
    private boolean _submenuPermisos = false;
    private boolean _menuUsuarios = false;
    private boolean _menuClientes = false;
    private boolean _menuVehiculos = false;
    private boolean _menuCitas = false;

    private FrmRoles frmRoles;
    private FrmPermisos frmPermisos;
    private FrmUsuarios frmUsuarios;
    private FrmClientes frmClientes;
    private FrmVehiculos frmVehiculos;
    private FrmCitas frmCitas;

    private FrmLogin frmLogin;

    /**
     * Creates new form FrmPrincipla
     */
    public FrmPrincipal() {
        initComponents();

        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        inicializarMenu();
    }

    public void inicializar() {
        setOperaciones();
    }

    private void setOperaciones() {
        if (FrmPrincipal.usuarioLogged == null) {
            this.dispose();
            return;
        }
        
        lbPrincipal.setText("[" + usuarioLogged.getRol().toInfo() + "] " + usuarioLogged.toInfo());

        int idRol = FrmPrincipal.usuarioLogged.getRol().getIdRol();
        List<Permiso> permisos = PermisoDAO.listByRolId(idRol);

        for (Permiso item : permisos) {
            if (item.getNombre().equals("menuAdministracionDePermisos")) {
                _menuAdministracionDePermisos = true;
            } else if (item.getNombre().equals("submenuRoles")) {
                _submenuRoles = true;
            } else if (item.getNombre().equals("submenuPermisos")) {
                _submenuPermisos = true;
            } else if (item.getNombre().equals("menuUsuarios")) {
                _menuUsuarios = true;
            } else if (item.getNombre().equals("menuClientes")) {
                _menuClientes = true;
            } else if (item.getNombre().equals("menuVehiculos")) {
                _menuVehiculos = true;
            } else if (item.getNombre().equals("menuCitas")) {
                _menuCitas = true;
            }
        }
        inicializarMenu();
    }

    private void inicializarMenu() {
        menuAdministracionDePermisos.setVisible(_menuAdministracionDePermisos);
        submenuRoles.setVisible(_submenuRoles);
        submenuPermisos.setVisible(_submenuPermisos);
        menuUsuarios.setVisible(_menuUsuarios);
        menuClientes.setVisible(_menuClientes);
        menuVehiculos.setVisible(_menuVehiculos);
        menuCitas.setVisible(_menuCitas);
    }

    private void cerrarSesion() {
        if (frmRoles != null && frmRoles.isShowing()) {
            frmRoles.dispose();
        }

        if (frmPermisos != null && frmPermisos.isShowing()) {
            frmPermisos.dispose();
        }

        if (frmUsuarios != null && frmUsuarios.isShowing()) {
            frmUsuarios.dispose();
        }

        if (frmClientes != null && frmClientes.isShowing()) {
            frmClientes.dispose();
        }

        if (frmVehiculos != null && frmVehiculos.isShowing()) {
            frmVehiculos.dispose();
        }

        if (frmCitas != null && frmCitas.isShowing()) {
            frmCitas.dispose();
        }

        this.dispose();

        frmLogin = new FrmLogin();
        frmLogin.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbPrincipal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuAdministracionDePermisos = new javax.swing.JMenu();
        submenuRoles = new javax.swing.JMenuItem();
        submenuPermisos = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuVehiculos = new javax.swing.JMenu();
        menuCitas = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(43, 75, 130));

        lbPrincipal.setFont(new java.awt.Font("Arial", 0, 28)); // NOI18N
        lbPrincipal.setForeground(new java.awt.Color(255, 255, 255));
        lbPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPrincipal.setText("LOGIN");
        lbPrincipal.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(251, 143, 76));
        jPanel4.setPreferredSize(new java.awt.Dimension(0, 15));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenuBar1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        jMenu1.setText("Sesión");
        jMenu1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jMenuItem1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        menuAdministracionDePermisos.setText("Administración de Permisos");
        menuAdministracionDePermisos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        submenuRoles.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        submenuRoles.setText("Roles");
        submenuRoles.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submenuRolesActionPerformed(evt);
            }
        });
        menuAdministracionDePermisos.add(submenuRoles);

        submenuPermisos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        submenuPermisos.setText("Permisos");
        submenuPermisos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                submenuPermisosActionPerformed(evt);
            }
        });
        menuAdministracionDePermisos.add(submenuPermisos);

        jMenuBar1.add(menuAdministracionDePermisos);

        menuUsuarios.setText("Usuarios");
        menuUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuUsuarios.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuUsuariosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuUsuarios);

        menuClientes.setText("Clientes");
        menuClientes.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuClientes.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuClientesMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuClientes);

        menuVehiculos.setText("Vehículos");
        menuVehiculos.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuVehiculos.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuVehiculosMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuVehiculos);

        menuCitas.setText("Citas");
        menuCitas.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        menuCitas.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                menuCitasMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCitas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        cerrarSesion();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void submenuRolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuRolesActionPerformed
        // TODO add your handling code here:
        if (frmRoles != null && frmRoles.isShowing()) {
            frmRoles.requestFocus();
            return;
        }
        frmRoles = new FrmRoles();
        frmRoles.inicializar();
        frmRoles.setVisible(true);
    }//GEN-LAST:event_submenuRolesActionPerformed

    private void submenuPermisosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submenuPermisosActionPerformed
        // TODO add your handling code here:
        if (frmPermisos != null && frmPermisos.isShowing()) {
            frmPermisos.requestFocus();
            return;
        }
        frmPermisos = new FrmPermisos();
        frmPermisos.inicializar();
        frmPermisos.setVisible(true);
    }//GEN-LAST:event_submenuPermisosActionPerformed

    private void menuUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuUsuariosMouseClicked
        // TODO add your handling code here:
        if (frmUsuarios != null && frmUsuarios.isShowing()) {
            frmUsuarios.requestFocus();
            return;
        }
        frmUsuarios = new FrmUsuarios();
        frmUsuarios.inicializar();
        frmUsuarios.setVisible(true);
    }//GEN-LAST:event_menuUsuariosMouseClicked

    private void menuClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuClientesMouseClicked
        // TODO add your handling code here:
        if (frmClientes != null && frmClientes.isShowing()) {
            frmUsuarios.requestFocus();
            return;
        }
        frmClientes = new FrmClientes();
        frmClientes.inicializar();
        frmClientes.setVisible(true);
    }//GEN-LAST:event_menuClientesMouseClicked

    private void menuVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuVehiculosMouseClicked
        // TODO add your handling code here:
        if (frmVehiculos != null && frmVehiculos.isShowing()) {
            frmVehiculos.requestFocus();
            return;
        }
        frmVehiculos = new FrmVehiculos();
        frmVehiculos.inicializar();
        frmVehiculos.setVisible(true);
    }//GEN-LAST:event_menuVehiculosMouseClicked

    private void menuCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCitasMouseClicked
        // TODO add your handling code here:
        if (frmCitas != null && frmCitas.isShowing()) {
            frmCitas.requestFocus();
            return;
        }
        frmCitas = new FrmCitas();
        frmCitas.inicializar();
        frmCitas.setVisible(true);
    }//GEN-LAST:event_menuCitasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbPrincipal;
    private javax.swing.JMenu menuAdministracionDePermisos;
    private javax.swing.JMenu menuCitas;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuUsuarios;
    private javax.swing.JMenu menuVehiculos;
    private javax.swing.JMenuItem submenuPermisos;
    private javax.swing.JMenuItem submenuRoles;
    // End of variables declaration//GEN-END:variables
}
